version: "3.9"

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"   # Redis server
      - "8001:8001"   # RedisInsight GUI
    volumes:
      - redis_data:/data

volumes:
  redis_data: